app/daily/urls.py
from django.urls import path

from daily.views import views
from daily.views import user_account
from daily.views import food

app_name = 'daily'

urlpatterns = [
    path('', user_account.user_login, name='user_login'),
    path('home', views.home, name='home'),
    path('register', user_account.register, name='register'),
    path('user_logout', user_account.user_logout, name='user_logout'),
    path('user_detail', user_account.user_detail, name='user_detail'),
    path('user_edit', user_account.user_edit, name='user_edit'),
    path('change_password', user_account.change_password, name='change_password'),
    path('user_delete', user_account.user_delete, name='user_delete'),

    path('food_input', food.food_input, name='food_input'),
    path('food_complete/<int:food_id>', food.food_complete, name='food_complete'),
    path('food_index', food.food_index, name='food_index'),
    path('food_search', food.food_search, name='food_search'),
    path('food_detail/<int:food_id>', food.food_detail, name='food_detail'),
    path('food_edit/<int:food_id>', food.food_edit, name='food_edit'),
    path('food_delete/<int:food_id>', food.food_delete, name='food_delete'),
    path('make_food_download_file', food.make_food_download_file, name='make_food_download_file'),
    path('make_food_detail_download_file/<int:food_id>', food.make_food_detail_download_file, name='make_food_detail_download_file'),
]

app/daily/models.py
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager
)
from django.db import models
from django.utils import timezone


class Users(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(max_length=255)
    age = models.PositiveIntegerField()
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    picture = models.FileField(blank=True, null=True, upload_to='profile/')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        db_table = 'users'


class UserSessions(models.Model):
    user_id = models.ForeignKey(Users, models.CASCADE, db_column='user_id')
    email = models.TextField(blank=True, null=True)
    session_key = models.TextField(db_index=True, unique=True)
    login_at = models.DateTimeField(null=True)
    last_used_at = models.DateTimeField(null=True)

    class Meta:
        db_table = 'user_sessions'


class UserAccessLogs(models.Model):
    request_at = models.DateTimeField(blank=True, null=True)
    response_at = models.DateTimeField(blank=True, null=True)
    user_id = models.ForeignKey(Users, models.CASCADE, db_column='user_id')
    username = models.TextField(blank=True)
    user_email = models.TextField(blank=True)
    request_method = models.TextField(blank=True)
    request_url = models.TextField(blank=True)
    referer = models.TextField(blank=True)
    source_ip = models.TextField(blank=True)
    user_agent = models.TextField(blank=True)
    session_id = models.IntegerField(blank=True)
    session_key = models.TextField(blank=True)
    response_time = models.IntegerField(blank=True)
    status_code = models.TextField(blank=True)

    class Meta:
        db_table = 'user_access_logs'


class PostFoods(models.Model):
    user_id = models.ForeignKey(Users, models.CASCADE, db_column='user_id')
    title = models.TextField(blank=True)
    food_name = models.TextField(blank=True)
    content = models.TextField(blank=True)
    image = models.FileField(blank=True, null=True, upload_to='foods/')
    ate_at = models.DateTimeField()
    created_at = models.DateTimeField(default=timezone.now)
    last_updated_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'post_foods'

app/daily/views/food.py
import csv
import logging
import os
import urllib.parse
from datetime import datetime
from django.contrib import messages
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from pytz import timezone

from django.conf import settings
from daily import forms
from daily.lib.common import utc_datetime_to_jst_datetime_format, jst_string_to_utc_datetime, delete_media_file
from daily.lib.food import FoodInfoDao
from daily.models import Users, PostFoods

logger = logging.getLogger('application')


def food_input(request):
    user = get_object_or_404(Users, id=request.user_id)
    food_input_form = forms.FoodInputForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if food_input_form.is_valid():
            food = food_input_form.save(commit=False)
            food.user_id = user
            food.save()
            return redirect('daily:food_complete', food_id=food.id)
        else:
            return render(request, 'daily/food/food_input.html', context={'food_input_form': food_input_form})
    else:
        return render(request, 'daily/food/food_input.html', context={'food_input_form': food_input_form})


def food_complete(request, food_id):
    return render(request, 'daily/food/food_complete.html', context={'food_id': food_id})


def food_index(request):
    return render(request, 'daily/food/food_index.html')


def food_search(request):
    if not request.method == "POST":
        return JsonResponse(status=400, data={})

    food_list = []
    food_lists = {}

    start_date = request.POST.get("start_date")
    end_date = request.POST.get("end_date")

    food_info_dao = FoodInfoDao(user_id=request.user_id)

    if start_date is None and end_date is None:
        # 投稿一覧画面テーブル初期表示処理
        post_foods = food_info_dao.get_food_info()
    else:
        # 食事日時検索条件指定処理
        start_date = jst_string_to_utc_datetime(start_date)
        end_date = jst_string_to_utc_datetime(end_date)
        post_foods = food_info_dao.get_food_info(start_date=start_date, end_date=end_date)

    if not post_foods:
        return JsonResponse(status=404, data={})
    else:
        for post_food in post_foods:
            food_list_dict = {}
            food_list_dict['href'] = "/food_detail/" + str(post_food.id)
            food_list_dict['title'] = post_food.title
            food_list_dict['food_name'] = post_food.food_name
            food_list_dict['ate_at'] = utc_datetime_to_jst_datetime_format(post_food.ate_at)
            food_list_dict['created_at'] = utc_datetime_to_jst_datetime_format(post_food.created_at)
            food_list.append(food_list_dict)
            food_lists['data'] = food_list
        return JsonResponse(food_lists)


def food_detail(request, food_id):
    food_info = get_object_or_404(PostFoods, id=food_id, user_id=request.user_id)
    return render(request, 'daily/food/food_detail.html', context={'food_info': food_info})


def food_edit(request, food_id):
    # 現在の食事投稿情報を取得
    current_food = get_object_or_404(PostFoods, id=food_id, user_id=request.user_id)
    # 画面表示用に食事日時をフォーマット
    current_food.ate_at = utc_datetime_to_jst_datetime_format(current_food.ate_at)
    food_edit_form = forms.FoodInputForm(request.POST or None, request.FILES or None, instance=current_food)

    if request.method == 'POST':
        # 現在の食事投稿画像情報を取得。存在しない場合Noneを代入
        current_image = str(current_food.image) if str(current_food.image) else None

        if food_edit_form.is_valid():
            food_edit_form.save()

            updated_food = get_object_or_404(PostFoods, id=food_id, user_id=request.user_id)
            # 更新後の食事投稿画像情報を取得。存在しない場合Noneを代入
            updated_image = str(updated_food.image) if str(updated_food.image) else None

            # 更新前後で食事投稿画像が異なるかつ、更新前画像が存在する場合に更新前画像ファイルを削除
            if current_image != updated_image and current_image is not None:
                delete_media_file(current_image)
            return redirect('daily:food_detail', food_id=food_id)
        else:
            return render(request, 'daily/food/food_edit.html', context={'food_edit_form': food_edit_form})
    else:
        return render(request, 'daily/food/food_edit.html', context={'food_edit_form': food_edit_form})


def food_delete(request, food_id):
    food_info = get_object_or_404(PostFoods, id=food_id, user_id=request.user_id)

    if request.method == "POST":
        # 削除する食事投稿画像情報を取得。存在しない場合Noneを代入
        food_image = str(food_info.image) if str(food_info.image) else None
        delete_media_file(food_image)

        try:
            food_info.delete()
        except Exception as e:
            logger.error(f'---food_id: {food_id} could not be deleted---')
            logger.error(e)
            raise Exception
        else:
            logger.info(f'---food_id:{food_id} was successfully deleted---')

        return HttpResponse(status=200)
    else:
        return render(request, 'daily/food/food_delete.html', context={'food_info': food_info})


def make_food_download_file(request):
    download_filename = 'food_file_'
    start_date = request.GET['start_date']
    end_date = request.GET['end_date']

    food_info_dao = FoodInfoDao(user_id=request.user_id)

    if start_date != '' or end_date != '':
        # 食事日時検索条件あり投稿一覧を取得
        start_date = jst_string_to_utc_datetime(start_date)
        end_date = jst_string_to_utc_datetime(end_date)
        post_foods = food_info_dao.get_food_info(start_date=start_date, end_date=end_date)
    else:
        # 食事日時検索条件なし投稿一覧を取得
        post_foods = food_info_dao.get_food_info()

    if not post_foods:
        raise Http404

    try:
        return make_food_download_csv(download_filename, post_foods)
    except Exception as e:
        logger.error(e)
        raise Exception


def make_food_detail_download_file(request, food_id):
    download_filename = 'food_detail_file_'

    try:
        food_info_rows = PostFoods.objects.filter(id=food_id, user_id=request.user_id)
        if not food_info_rows:
            raise Http404
        return make_food_download_csv(download_filename, food_info_rows)
    except Exception as e:
        logger.error(e)
        raise Exception


def make_food_download_csv(download_filename, rows):
    file_contents = []
    file_content = []

    # ダウンロード用csvファイル名設定
    current_date = datetime.now()
    current_date_str = current_date.strftime('%Y%m%d%H%M')
    filename = download_filename + current_date_str + '.csv'

    # csvヘッダ設定
    csv_header = [
        'id',
        'タイトル',
        '料理名',
        '内容',
        '食事日時',
        '投稿日時'
    ]

    file_contents.append(csv_header)

    # csv内容設定
    for i, row in enumerate(rows, start=1):
        file_content.append(i)
        file_content.append(row.title)
        file_content.append(row.food_name)
        file_content.append(row.content)
        ate_at = utc_datetime_to_jst_datetime_format(row.ate_at)
        file_content.append(ate_at)
        created_at = utc_datetime_to_jst_datetime_format(row.created_at)
        file_content.append(created_at)

        file_contents.append(file_content)
        file_content = []

    # csv出力
    response = HttpResponse(content_type='text/csv;')
    response['Content-Disposition'] = "attachment; filename*=utf-8''%s" % urllib.parse.quote(filename, encoding='utf-8')

    writer = csv.writer(response)
    for line in file_contents:
        writer.writerow(line)

    return response

app/daily/views/user_account.py
import logging
import os
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.crypto import get_random_string

from django.conf import settings
from const.const import COOKIE_SESSION_KEY
from daily import forms
from daily.lib.common import delete_media_file
from daily.models import Users, UserSessions, PostFoods

logger = logging.getLogger('application')


def register(request):
    register_form = forms.RegisterForm(request.POST or None)
    if register_form.is_valid():
        try:
            register_form.save()
            messages.success(request, 'ユーザーを作成しました。')
            return redirect('daily:home')
        except ValidationError as e:
            register_form.add_error('password', e)
    return render(request, 'daily/user_account/register.html', context={'register_form': register_form})


def user_login(request):
    login_form = forms.LoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if user:
            if user.is_active:
                # ログイン処理(下記コメントアウト処理はLoginView実装時のものだが、Middleware側処理daily-session-keyにて管理するため不要となる。)
                # login(request, user)

                response = redirect('daily:home')
                session_key = get_random_string(64)

                # ログインセッション作成
                UserSessions.objects.create(
                    user_id=user, email=user.email, session_key=session_key, login_at=datetime.now(),
                    last_used_at=datetime.now()
                )
                # ログインセッションをクッキーに設定
                response.set_cookie(COOKIE_SESSION_KEY, session_key)
                return response
            else:
                messages.warning(request, 'ユーザーが存在しません。')
        else:
            messages.warning(request, 'メールアドレスまたはパスワードが間違っています。')
    return render(request, 'daily/user_account/user_login.html', context={'login_form': login_form})


def user_logout(request):
    # ログアウト処理(下記コメントアウト処理はLoginView実装時のものだが、Middleware側処理daily-session-keyにて管理するため不要となる。)
    # logout(request)
    messages.success(request, 'ログアウトしました。')
    return redirect('daily:user_login')


def user_detail(request):
    user_info = get_object_or_404(Users, id=request.user_id)
    return render(request, 'daily/user_account/user_detail.html', context={'user_info': user_info})


def user_edit(request):
    # 現在のユーザー情報を取得
    current_user = get_object_or_404(Users, id=request.user_id)
    user_edit_form = forms.UserEditForm(request.POST or None, request.FILES or None, instance=current_user)

    if request.method == 'POST':
        # 現在のユーザー画像情報を取得。存在しない場合Noneを代入
        current_picture = str(current_user.picture) if str(current_user.picture) else None

        if user_edit_form.is_valid():
            user_edit_form.save()

            updated_user = get_object_or_404(Users, id=request.user_id)
            # 更新後のユーザー画像情報を取得。存在しない場合Noneを代入
            updated_picture = str(updated_user.picture) if str(updated_user.picture) else None

            # 更新前後でユーザー画像が異なるかつ、更新前画像が存在する場合に更新前画像ファイルを削除
            if current_picture != updated_picture and current_picture is not None:
                delete_media_file(current_picture)
            return redirect('daily:user_detail')
        else:
            return render(request, 'daily/user_account/user_edit.html', context={'user_edit_form': user_edit_form})
    else:
        return render(request, 'daily/user_account/user_edit.html', context={'user_edit_form': user_edit_form})


def change_password(request):
    user = get_object_or_404(Users, id=request.user_id)
    password_change_form = forms.PasswordChangeForm(request.POST or None, instance=user)
    if password_change_form.is_valid():
        try:
            password_change_form.save()
            messages.success(request, 'パスワードの更新が完了しました。')
            # パスワード更新後、セッション情報を更新。(下記コメントアウト処理はLoginView実装時のものだが、Middleware側処理daily-session-keyにて管理するため不要となる。)
            # update_session_auth_hash(request, user)
        except ValidationError as e:
            password_change_form.add_error('password', e)
    return render(request, 'daily/user_account/change_password.html', context={'password_change_form': password_change_form})


def user_delete(request):
    user_info = get_object_or_404(Users, id=request.user_id)

    if request.method == "POST":
        food_info = PostFoods.objects.filter(user_id=request.user_id)
        for i, food_info_row in enumerate(food_info):
            food_image = str(food_info_row.image) if str(food_info_row.image) else None
            # 削除対象のユーザーに紐づく投稿画像ファイルを削除
            delete_media_file(food_image)
        try:
            # 削除対象のユーザーに紐づく投稿データを削除
            food_info.delete()
        except Exception as e:
            logger.error(e)

        # 削除するユーザー画像情報を取得。存在しない場合Noneを代入
        user_image = str(user_info.picture) if str(user_info.picture) else None
        delete_media_file(user_image)
        try:
            user_info.delete()
        except Exception as e:
            logger.error(f'---user_id: {request.user_id} could not be deleted---')
            logger.error(e)
            raise Exception
        logger.info(f'---user_id: {request.user_id} was successfully deleted---')

        return HttpResponse(status=200)
    else:
        return render(request, 'daily/user_account/user_delete.html', context={'user_info': user_info})

app/daily/views/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'daily/home.html')

app/templates/daily/food/food_base.html
{% load static %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/food.css' %}">
<script type="text/javascript" src="{% static 'js/food.js' %}"></script>
<script type="text/javascript" src="{% static 'js/const.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common_validator.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" integrity="sha512-bYPO5jmStZ9WI2602V2zaivdAnbAhtfzmxnEGh9RwtlI00I9s8ulGe4oBa5XxiC6tCITJH/QG70jswBhbLkxPw==" crossorigin="anonymous" />

app/templates/daily/food/food_complete.html
{% extends "base.html" %}
{% block content %}

<h4>投稿が完了しました。</h4>

<a href="{% url 'daily:food_input' %}" style="margin: 5px;"><button>投稿画面へ</button></a>
<a href="{% url 'daily:food_detail' food_id %}" style="margin: 5px;"><button>投稿詳細画面へ</button></a>
{% endblock %}

app/templates/daily/food/food_delete.html
{% extends "base.html" %}
{% block content %}
{% include "daily/food/food_base.html" %}

<h4>投稿削除</h4>

    {% if food_info.image %}
    <img src="/media/{{ food_info.image }}" alt="投稿画像" width="380" height="232">
    {% else %}
    <img src="/media/foods/no_image.jpg" alt="投稿画像" width="380" height="232">
    {% endif %}
    <p>タイトル：{{ food_info.title }}</p>
    <p>料理名：{{ food_info.food_name }}</p>
    <p>内容：{{ food_info.content }}</p>
    <p>食事日時：{{ food_info.ate_at }}</p>
    <p>投稿日時：{{ food_info.created_at }}</p>

    <p class="delete-message" style="color: #660033;"></p>
    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
    <button id="food_delete_button" type="button" onclick="food_delete({{ food_info.id }})">投稿を削除する</button>

<script>
let i = 3
const interval_func = function() {
    if(i === 0){
        clearInterval(timer);
        location.href="{% url 'daily:food_index' %}";
    }
    $('.delete-message').text(i + '秒後に投稿一覧画面へ遷移します')
    i = i - 1;
}

function food_delete(food_id){
    $('#food_delete_button').attr('disabled', 'disabled');
    if(confirm('この投稿を本当に削除しますか？')) {
        $.ajax({
            url: '/food_delete/' + food_id,
            type: "POST",
            headers: {
                "X-CSRFToken": get_cookie('csrftoken'),
            },
        }).done(function () {
            $('.delete-message').text('この投稿を削除しました')
            $('#food_delete_button').before('<progress></progress><br>');
            timer = setInterval(interval_func, 1000)
        }).fail(function () {
            $('.delete-message').text('投稿の削除に失敗しました')
        }).always(function (data) {
        });
    }else {
        $('#food_delete_button').prop('disabled', '');
    }
}
</script>

{% endblock %}

app/templates/daily/food/food_detail.html
{% extends "base.html" %}
{% block content %}
{% include "daily/food/food_base.html" %}

{% if messages %}
  {% for message in messages %}
    <div>{{ message.message }}</div>
  {% endfor %}
{% endif %}

<h4>投稿詳細</h4>

    {% if food_info.image %}
    <img src="/media/{{ food_info.image }}" alt="投稿画像" width="380" height="232">
    {% else %}
    <img src="/media/foods/no_image.jpg" alt="投稿画像" width="380" height="232">
    {% endif %}
    <p>タイトル：{{ food_info.title }}</p>
    <p>料理名：{{ food_info.food_name }}</p>
    <p>内容：{{ food_info.content }}</p>
    <p>食事日時：{{ food_info.ate_at }}</p>
    <p>投稿日時：{{ food_info.created_at }}</p>

    <button id="csv_download_button" type="button" onclick="location.href='{% url 'daily:make_food_detail_download_file' food_info.id %}'">CSVファイルをダウンロード</button>

    <br><br>
    <a href="{% url 'daily:food_edit' food_info.id %}"><button class="to_food_edit_button">投稿編集へ</button></a>
    <a href="{% url 'daily:food_delete' food_info.id %}"><button class="to_food_delete_button">投稿削除へ</button></a>

{% endblock %}

app/templates/daily/food/food_edit.html
{% extends "base.html" %}
{% block content %}
{% include "daily/food/food_base.html" %}

{% if messages %}
  {% for message in messages %}
    <div>{{ message.message }}</div>
  {% endfor %}
{% endif %}

<h4>投稿編集</h4>

<div class="form">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ food_edit_form.as_p }}
        <input id="submit" type="submit" value="更新">
    </form>
</div>

<script type="text/javascript">
      window.onload = $(function () {
          FoodInputController();

          date = new Date(new Date().setHours(0, 0));
          $('#id_ate_at').datetimepicker({
            step:10, //10分刻み
            format:'Y-m-d H:i', //フォーマット指定
            maxDate: date, //指定可能日は最大で当日までに指定
          });
      });
</script>

{% endblock %}

app/templates/daily/food/food_index.html
{% extends "base.html" %}
{% block content %}
{% include "daily/food/food_base.html" %}
<style type="text/css">
  #food_table {
    width: 100% !important;
    min-width: 100% !important;
  }
</style>

<link rel="stylesheet" type="text/css" href="static/js/DataTables/datatables.min.css"/>
<script type="text/javascript" src="static/js/DataTables/datatables.min.js"></script>

<h4>食事投稿一覧</h4>

<div class="food_search_box">
  食事日時範囲検索:
  <input type="text" id="start_date">～
  <input type="text" id="end_date">
  <button id="food_search" onclick="search_with_date_range()" disabled="disabled"><span>検索</span></button>
</div>

<table id="food_table" class="table table-bordered">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>料理名</th>
      <th>食事日時</th>
      <th>投稿日時</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<form>
  <button id="csv_download_button" type="button" disabled="disabled" onclick="csv_download()">csvファイルをダウンロード</button>
  <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
</form>

<script>
  function create_datatable() {
    $("#food_table").DataTable({
      // デフォルトでソートとするカラムを設定
      "order": [ [ 2, "desc" ] ],
      // テーブル内再描画時に既存のテーブル削除をTrueとする
      "destroy": true,
      // 非同期処理
      "ajax": {
        "url": "{% url 'daily:food_search' %}",
        "type": "POST",
        "data": function(d) {
          food_filter = sessionStorage.getItem('FoodFilter') === null ? "" : JSON.parse(sessionStorage.getItem('FoodFilter'));
          if (food_filter != ""){
           d.start_date = food_filter['start_date'];
           d.end_date = food_filter['end_date'];
          }
        },
        "error": function(jqXHR, textStatus, errorThrown) {
          $('#food_table').DataTable().clear().draw();
          $('#food_search').prop('disabled', '');
        },
        "beforeSend": function(jqXHR, settings) {
          jqXHR.setRequestHeader("X-CSRFToken", get_cookie('csrftoken'));
        }
      },
      // ajax返却値を元に各tdを作成
      "columns": [
        { data: 'title' },
        { data: 'food_name' },
        { data: 'ate_at' },
        { data: 'created_at' },
      ],
      // ajax返却値を元に各trに対しリンクを作成
      "createdRow": function(row, data, dataIndex) {
        $(row).attr('data-href', data.href)
        $(row).addClass("table-link")
        $(row).click(function(e) {
            window.location = $(e.target).closest('tr').data('href');
        });
        // テーブル描画後、検索ボタンを活性化
        $('#food_search').prop('disabled', '');
        // テーブル描画後、csvダウンロードボタンを活性化
        $('#csv_download_button').prop('disabled', '');
      },
    });
  }

  function search_with_date_range() {
    $('#food_search').attr('disabled', 'disabled');
    $('#csv_download_button').attr('disabled', 'disabled');
    let FilterItems = {
      'start_date': document.getElementById("start_date").value,
      'end_date': document.getElementById("end_date").value,
    };

    sessionStorage.removeItem('FoodFilter');
    sessionStorage.setItem('FoodFilter', JSON.stringify(FilterItems));

    create_datatable();
  }

  function csv_download() {
    $('#csv_download_button').attr('disabled', 'disabled');

    let start_date = ''
    let end_date = ''
    let FilterItems = sessionStorage.getItem('FoodFilter') === null ? "" : JSON.parse(sessionStorage.getItem('FoodFilter'));
    if (FilterItems != ""){
      start_date = FilterItems.start_date;
      end_date = FilterItems.end_date;
    }

    location.href="{% url 'daily:make_food_download_file' %}?start_date=" + start_date + "&end_date=" + end_date;
  }

  $(document).ready(function () {
    sessionStorage.removeItem('FoodFilter');

    $('#start_date, #end_date').datetimepicker({
      step:10, //10分刻み
      format:'Y-m-d H:i', //フォーマット指定
    });

    create_datatable();
  });
</script>

{% endblock %}

app/templates/daily/food/food_input.html
{% extends "base.html" %}
{% block content %}
{% include "daily/food/food_base.html" %}

<h4>食事を投稿しよう！</h4>

<div class="form">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ food_input_form.as_p }}
        <input id="submit" type="submit" value="投稿" disabled="disabled">
    </form>
</div>

<script type="text/javascript">
      window.onload = $(function () {
          FoodInputController();

          date = new Date(new Date().setHours(0, 0));
          $('#id_ate_at').datetimepicker({
            step:10, //10分刻み
            format:'Y-m-d H:i', //フォーマット指定
            maxDate: date, //指定可能日は最大で当日までに指定
          });
      });
</script>

{% endblock %}