app/daily/urls.py
from django.urls import path

from daily.views import views
from daily.views import user_account
from daily.views import food

app_name = 'daily'

urlpatterns = [
    path('', user_account.user_login, name='user_login'),
    path('home', views.home, name='home'),
    path('register', user_account.register, name='register'),
    path('user_logout', user_account.user_logout, name='user_logout'),
    path('user_detail', user_account.user_detail, name='user_detail'),
    path('user_edit', user_account.user_edit, name='user_edit'),
    path('change_password', user_account.change_password, name='change_password'),
    path('user_delete', user_account.user_delete, name='user_delete'),

    path('food_input', food.food_input, name='food_input'),
    path('food_complete/<int:food_id>', food.food_complete, name='food_complete'),
    path('food_index', food.food_index, name='food_index'),
    path('food_search', food.food_search, name='food_search'),
    path('food_detail/<int:food_id>', food.food_detail, name='food_detail'),
    path('food_edit/<int:food_id>', food.food_edit, name='food_edit'),
    path('food_delete/<int:food_id>', food.food_delete, name='food_delete'),
    path('make_food_download_file', food.make_food_download_file, name='make_food_download_file'),
    path('make_food_detail_download_file/<int:food_id>', food.make_food_detail_download_file, name='make_food_detail_download_file'),
]

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/index.css' %}">
        <script type="text/javascript" src="{% static 'js/index.js' %}"></script>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <!-- 下記2ファイルはメニューのプルダウン用 -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <title>Daily</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #E6DFB7; margin-bottom: 5px;">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="navbar-brand nav-link" href="{% url 'daily:home' %}">Home</a></li>
            </ul>
            <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="navbar-brand nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ユーザー</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'daily:user_detail' %}">ユーザー詳細</a>
                        <a class="dropdown-item" href="{% url 'daily:user_edit' %}">ユーザー編集</a>
                    </div>
                <li class="nav-item dropdown">
                    <a class="navbar-brand nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">投稿</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'daily:food_input' %}">投稿</a>
                        <a class="dropdown-item" href="{% url 'daily:food_index' %}">投稿一覧</a>
                    </div>
                </li>
                <li class="nav-item"><a class="navbar-brand nav-link" href="{% url 'daily:user_logout' %}">Logout</a></li>
            </ul>
            </div>
        </nav>
        <div class="context">
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>